template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "tuvi1240"
__REPO__ = "lang-tyv"
__UND2C__ = "tyv"
__UNDEFINED__ = "Tuvinian"
__UND__ = "tyv"
