template = "https://github.com/giellalt/template-lang-und"
rev_id = 327
template_sha = "65f0d288ed0f81badfaa2043de3fd624c73adb20"

[replacements]
__GLOTTOLOG_ID__ = "tuvi1240"
__REPO__ = "lang-tyv"
__UND2C__ = "tyv"
__UNDEFINED__ = "Tuvinian"
__UND__ = "tyv"
