template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "tuvi1240"
__REPO__ = "lang-tyv"
__UND2C__ = "tyv"
__UNDEFINED__ = "Tuvinian"
__UND__ = "tyv"
