[package]
name = "tyv"
human_name = "Tuvinian"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tyv]
filename = "tyv-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tyv"
platform = "windows"
uuid = "EB5C24F5-CCE3-4D63-ADE0-75834C656734"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.tyv"
package = "speller-tyv"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tyv-mso"
platform = "windows"
uuid = "08CCE5BB-09A4-4D3C-A45C-BC03AFA419F5"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tyv"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
